defmodule :"Elixir.Tunez.Repo.Migrations.Artist-add-previous-names" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:artists) do
      add :previous_names, :text
    end
  end

  def down do
    alter table(:artists) do
      remove :previous_names
    end
  end
end
